### ISSUE TITLE
'module' object has no attribute 'OpenEx'

### ISSUE THREAD

**Issue by hishamkaram** [GeoNode/django-osgeo-importer#130]
I want to use django-osgeo-importer with geonode but this error appear when i try to upload any layer?
```
| Traceback (most recent call last):
|   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
|     response = wrapped_callback(request, *callback_args, **callback_kwargs)
|   File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
|     return view_func(request, *args, **kwargs)
|   File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
|     return self.dispatch(request, *args, **kwargs)
|   File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
|     return handler(request, *args, **kwargs)
|   File "/usr/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 214, in post
|     if form.is_valid():
|   File "/usr/local/lib/python2.7/site-packages/django/forms/forms.py", line 184, in is_valid
|     return self.is_bound and not self.errors
|   File "/usr/local/lib/python2.7/site-packages/django/forms/forms.py", line 176, in errors
|     self.full_clean()
|   File "/usr/local/lib/python2.7/site-packages/django/forms/forms.py", line 393, in full_clean
|     self._clean_form()
|   File "/usr/local/lib/python2.7/site-packages/django/forms/forms.py", line 417, in _clean_form
|     cleaned_data = self.clean()
|   File "/usr/local/lib/python2.7/site-packages/osgeo_importer/forms.py", line 64, in clean
|     if not validate_inspector_can_read(cleaned_file_path):
|   File "/usr/local/lib/python2.7/site-packages/osgeo_importer/validators.py", line 51, in validate_inspector_can_read
|     data, inspector = importer.open_source_datastore(filename)
|   File "/usr/local/lib/python2.7/site-packages/osgeo_importer/importers.py", line 160, in open_source_datastore
|     return self.open_datastore(connection_string, self.source_inspectors, *args, **kwargs)
|   File "/usr/local/lib/python2.7/site-packages/osgeo_importer/importers.py", line 148, in open_datastore
|     data = insp.open()
|   File "/usr/local/lib/python2.7/site-packages/osgeo_importer/inspectors.py", line 145, in open
|     self.data = gdal.OpenEx(filename, open_options=open_options)
| AttributeError: 'module' object has no attribute 'OpenEx'
```
settings:
```
......
INSTALLED_APPS += ('osgeo_importer',)
#### osgeo_importer settings
OSGEO_DATASTORE = 'datastore'
OSGEO_IMPORTER_GEONODE_ENABLED = True
OSGEO_IMPORTER_VALID_EXTENSIONS = [
    'shp', 'shx', 'prj', 'dbf', 'kml', 'geojson', 'json', 'tif', 'tiff',
    'gpkg', 'csv', 'zip', 'xml', 'sld'
]
IMPORT_HANDLERS = [
    # If GeoServer handlers are enabled, you must have an instance of geoserver running.
    # Warning: the order of the handlers here matters.
    'osgeo_importer.handlers.FieldConverterHandler',
    'osgeo_importer.handlers.geoserver.GeoserverPublishHandler',
    'osgeo_importer.handlers.geoserver.GeoserverPublishCoverageHandler',
    'osgeo_importer.handlers.geoserver.GeoServerTimeHandler',
    'osgeo_importer.handlers.geoserver.GeoWebCacheHandler',
    'osgeo_importer.handlers.geoserver.GeoServerBoundsHandler',
    'osgeo_importer.handlers.geoserver.GenericSLDHandler',
    'osgeo_importer.handlers.geonode.GeoNodePublishHandler',
#     'osgeo_importer.handlers.mapproxy.publish_handler.MapProxyGPKGTilePublishHandler',
    'osgeo_importer.handlers.geoserver.GeoServerStyleHandler',
    'osgeo_importer.handlers.geonode.GeoNodeMetadataHandler'
]

PROJECTION_DIRECTORY = os.path.join(PROJECT_ROOT, "data")
DATABASES['datastore']= {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'test_datastore',
        'USER' : 'postgres',
        'PASSWORD' : 'root',
        'HOST' : 'localhost',
        'PORT' : '5432',
    }
.....
```

**Comment by jj0hns0n** [comment]
Pretty sure its related to using an older copy of gdal or the gdal
bindings. Can you check what gdal version you are on and that the python
bindings are in your virtualenv.

**Comment by hishamkaram** [comment]
```
>>> import osgeo.gdal
>>> print osgeo.gdal.__version__
1.10.1
```

**Comment by hishamkaram** [comment]
I am using this Docker image 
```
FROM python:2.7.13

# Some stuff that everyone has been copy-pasting
# since the dawn of time.
ENV PYTHONUNBUFFERED 1

# Install some necessary things.
RUN apt-get update
RUN apt-get install -y swig libssl-dev dpkg-dev netcat gcc \
                gettext \
                postgresql-client libpq-dev \
                sqlite3 \
                python-gdal python-psycopg2 \
                python-imaging python-lxml \
                python-dev libgdal-dev \
                python-ldap \
                libmemcached-dev libsasl2-dev zlib1g-dev \
                python-pylibmc \
        --no-install-recommends && rm -rf /var/lib/apt/lists/*

RUN mkdir /code
WORKDIR /code

# Install our requirements.
RUN pip install GDAL==1.10 --global-option=build_ext --global-option="-I/usr/include/gdal"
```

**Comment by jj0hns0n** [comment]
You need gdal > 2.0, you can get it from ubuntugis.

**Comment by hishamkaram** [comment]
Working Fine <3

**Comment by jj0hns0n** [comment]
You might file an issue that we _should_ support 1.x but this should
certainly be documented better that only 2.x is currently supported.
