### ISSUE TITLE
Error uploading previously working .zip

### ISSUE THREAD

**Issue by JivanAmara** [GeoNode/django-osgeo-importer#138]
Using /one-shot-demo/ to upload deleteme.zip worked previously but now fails.  I think the problem was introduced with commit 9187ab0fb184.

Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/jivan/.projects/django-osgeo-importer/osgeo_importer/utils.py", line 550, in import_all_layers
    upload_layer.upload_file.id, configuration_options=configuration_options
  File "/home/jivan/.virtualenvs/django-osgeo-importer/local/lib/python2.7/site-packages/celery/app/task.py", line 453, in delay
    return self.apply_async(args, kwargs)
  File "/home/jivan/.virtualenvs/django-osgeo-importer/local/lib/python2.7/site-packages/celery/app/task.py", line 551, in apply_async
    link=link, link_error=link_error, **options)
  File "/home/jivan/.virtualenvs/django-osgeo-importer/local/lib/python2.7/site-packages/celery/app/task.py", line 743, in apply
    request=request, propagate=throw)
  File "/home/jivan/.virtualenvs/django-osgeo-importer/local/lib/python2.7/site-packages/celery/app/trace.py", line 355, in eager_trace_task
    uuid, args, kwargs, request)
  File "/home/jivan/.virtualenvs/django-osgeo-importer/local/lib/python2.7/site-packages/celery/app/trace.py", line 253, in trace_task
    I, R, state, retval = on_error(task_request, exc, uuid)
  File "/home/jivan/.virtualenvs/django-osgeo-importer/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/jivan/.projects/django-osgeo-importer/osgeo_importer/tasks.py", line 87, in import_object
    gi.handle(configuration_options=configuration_options, request_cookies=request_cookies, request_user=request_user)
  File "/home/jivan/.projects/django-osgeo-importer/osgeo_importer/importers.py", line 116, in handle
    config['handler_results'] = self.run_import_handlers(layer, config, **kwargs)
  File "/home/jivan/.projects/django-osgeo-importer/osgeo_importer/importers.py", line 131, in run_import_handlers
    self.handler_results.append({type(handler).__name__: handler.handle(layer, layer_config, *args, **kwargs)})
  File "/home/jivan/.projects/django-osgeo-importer/osgeo_importer/handlers/__init__.py", line 20, in func_wrapper
    return func(self, *args, **kwargs)
  File "/home/jivan/.projects/django-osgeo-importer/osgeo_importer/handlers/geoserver/__init__.py", line 240, in handle
    store = self.get_or_create_datastore(layer_config, request_user)
  File "/home/jivan/.projects/django-osgeo-importer/osgeo_importer/handlers/geoserver/__init__.py", line 150, in get_or_create_datastore
    if connection_string['type'] == 'geogig':
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by JivanAmara** [comment]
[deleteme.zip](https://github.com/GeoNode/django-osgeo-importer/files/865634/deleteme.zip)

**Comment by Coop56** [comment]
This should be resolved with this PR - https://github.com/GeoNode/django-osgeo-importer/pull/139
